### ISSUE TITLE
Vector Library Rewrite Required

### ISSUE THREAD

**Issue by Pencilcaseman** [LibRapid/librapid#106]
Vector library is currently unmaintainable. A rewrite is needed to improve functionality and ease of development

**Comment by NervousNullPtr** [comment]
How is the library unmaintainable? The code doesn't seem *too* bad.

**Comment by Pencilcaseman** [comment]
Code isn't awful, but the implementation of the seperate, more highly optimised vector types needs to change because it's just such a pain to add a new function. I'm thinking some sort of macro for different vector dimensions which can then just replace a single operator with the expanded loop/calculation.

I deleted the more optimised Vec3 implementation btw. I'll add it back when I have sorted out the rest of it

But I'm thinking something along these lines, except a more versatile approach and having one defined for each optimised vector type. Currently that'll be Vec2, Vec3 and Vec4, and then the VecN type has to store a list of values, so by definition can't be as fast but should work just fine anyway.

```cpp
#define IMPL_VEC_OP(OP)                                                                            \
	template<typename DTYPE, int64_t dims>                                                         \
	LR_INLINE Vec<DTYPE, dims> OP(const Vec<DTYPE, dims> &vec) {                                   \
		Vec<DTYPE, dims> res;                                                                      \
		for (int64_t i = 0; i < dims; ++i) { res[i] = ::librapid::OP(vec[i]); }                    \
		return res;                                                                                \
	}

	IMPL_VEC_OP(sin)
	IMPL_VEC_OP(cos)
	IMPL_VEC_OP(tan)
```
