### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Pencilcaseman** [LibRapid/librapid#95]
Does what it says on the can. Write some ****ing documentation.

**Comment by athulmekkoth** [comment]
can I work on this?

**Comment by Pencilcaseman** [comment]
If you want to, that'd be amazing!

**Comment by NervousNullPtr** [comment]
Maybe I'll also work on the docs a bit.
Depends on how much time I have available, but then the docs are finally getting somewhere

**Comment by Pencilcaseman** [comment]
Awesome guys! If you want to build the documentation, just run `make html` in the `docs` folder. The documentation for the current build is also available online at [read the docs](https://librapid.readthedocs.io/en/latest/), but as you can probably tell it's almost entirely useless `:')`
